"""Split assignment must be deterministic forever (SPEC §3.4).

The hard-coded expectations below are the whole point: if a refactor changes the
hash, the digest slice, or the bucket boundaries, documents silently migrate
between train and eval and every downstream number becomes untrustworthy.
"""

from __future__ import annotations

import subprocess
import sys
import textwrap
from collections import Counter

from sxl.splits import bucket_for, split_for

# Computed from the SPEC §3.4 formula; hand-checked, not generated by the code.
KNOWN = {
    "jp_000001": ("train", 51),
    "jp_000012": ("eval_pool", 1),
    "jp_000065": ("dev", 8),
}


def test_known_doc_ids_land_where_spec_says():
    for doc_id, (split, bucket) in KNOWN.items():
        assert bucket_for(doc_id) == bucket
        assert split_for(doc_id) == split


def test_split_is_stable_within_a_process():
    assert [split_for("jp_000012") for _ in range(5)] == ["eval_pool"] * 5


def test_split_is_stable_across_processes():
    """A fresh interpreter (new PYTHONHASHSEED) must agree."""
    code = textwrap.dedent(
        """
        from sxl.splits import split_for
        print(",".join(split_for(d) for d in ("jp_000001", "jp_000012", "jp_000065")))
        """
    )
    out = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True, check=True)
    assert out.stdout.strip() == "train,eval_pool,dev"


def test_buckets_are_in_range():
    assert all(0 <= bucket_for(f"jp_{i:06d}") <= 99 for i in range(1000))


def test_proportions_land_near_5_5_90():
    n = 10_000
    counts = Counter(split_for(f"jp_{i:06d}") for i in range(n))
    pct = {k: 100 * v / n for k, v in counts.items()}
    assert abs(pct["eval_pool"] - 5) <= 2, pct
    assert abs(pct["dev"] - 5) <= 2, pct
    assert abs(pct["train"] - 90) <= 2, pct


def test_eval_pool_bucket_can_supply_the_340_docs_f3_needs():
    """SPEC §3.4: 7,500 docs must yield >= 340 eval_pool rows."""
    n_eval = sum(split_for(f"jp_{i:06d}") == "eval_pool" for i in range(7500))
    assert n_eval >= 340, n_eval
